package db;

// Generated Apr 7, 2015 10:37:15 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * DeptEmp generated by hbm2java
 */
public class DeptEmp implements java.io.Serializable {

	private DeptEmpId id;
	private Date fromDate;
	private Date toDate;

	public DeptEmp() {
	}

	public DeptEmp(DeptEmpId id, Date fromDate, Date toDate) {
		this.id = id;
		this.fromDate = fromDate;
		this.toDate = toDate;
	}

	public DeptEmpId getId() {
		return this.id;
	}

	public void setId(DeptEmpId id) {
		this.id = id;
	}

	public Date getFromDate() {
		return this.fromDate;
	}

	public void setFromDate(Date fromDate) {
		this.fromDate = fromDate;
	}

	public Date getToDate() {
		return this.toDate;
	}

	public void setToDate(Date toDate) {
		this.toDate = toDate;
	}

}
