package db;

// Generated Apr 7, 2015 10:37:15 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * DeptManager generated by hbm2java
 */
public class DeptManager implements java.io.Serializable {

	private DeptManagerId id;
	private Date fromDate;
	private Date toDate;

	public DeptManager() {
	}

	public DeptManager(DeptManagerId id, Date fromDate, Date toDate) {
		this.id = id;
		this.fromDate = fromDate;
		this.toDate = toDate;
	}

	public DeptManagerId getId() {
		return this.id;
	}

	public void setId(DeptManagerId id) {
		this.id = id;
	}

	public Date getFromDate() {
		return this.fromDate;
	}

	public void setFromDate(Date fromDate) {
		this.fromDate = fromDate;
	}

	public Date getToDate() {
		return this.toDate;
	}

	public void setToDate(Date toDate) {
		this.toDate = toDate;
	}

}
