package db;

// Generated Apr 7, 2015 10:37:15 PM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Salaries generated by hbm2java
 */
public class Salaries implements java.io.Serializable {

	private SalariesId id;
	private int salary;
	private Date toDate;

	public Salaries() {
	}

	public Salaries(SalariesId id, int salary, Date toDate) {
		this.id = id;
		this.salary = salary;
		this.toDate = toDate;
	}

	public SalariesId getId() {
		return this.id;
	}

	public void setId(SalariesId id) {
		this.id = id;
	}

	public int getSalary() {
		return this.salary;
	}

	public void setSalary(int salary) {
		this.salary = salary;
	}

	public Date getToDate() {
		return this.toDate;
	}

	public void setToDate(Date toDate) {
		this.toDate = toDate;
	}

}
